input {
  file {
    path => "/usr/share/logstash/clickstream_data/weblog.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  mutate {
    gsub => ["message", "^\xEF\xBB\xBF", ""]
  }

  csv {
    separator => ","
    columns => ["client_ip", "timestamp_raw", "request", "response"]
  }

  mutate {
    gsub => ["timestamp_raw", "^\[", ""]
  }

  date {
    match => ["timestamp_raw", "dd/MMM/yyyy:HH:mm:ss"]
    target => "@timestamp"
    timezone => "UTC"
  }

  mutate {
    convert => { "response" => "integer" }
    remove_field => ["timestamp_raw", "message"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "clickstream-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
